WINDOW_TITLE = "Auto Tabs"
WINDOW_MIN_WIDTH = 300
WINDOW_MIN_HEIGHT = 200

PROFILE_PADDING_X = 20
PROFILE_PADDING_Y = 20
WIDGET_PADDING_X = 10
WIDGET_PADDING_Y = 10

PROFILE_FONT = ("Arial", 14)
DEFAULT_PROFILE_COLOUR = "#f0f0f0"
